# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 385527c1c553899e76ee818034ca875f5e15baa1e3287308df7259320e0f30a57d52d53d50afda46dc89591bf10e45dc6e87a59467642c250ddc4b1db8ac5341

test:
  secret_key_base: 0cf83dae811010b9b3bd3d2896cc08f233e3efa1d0fdd92bcf6c00de41fe105ba63bda86acb891b9531fdb081bddef97509de43e56a2c8f1f69b0d4441c2d49d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
